import Head from "next/head";
import Image from "next/image";
import { ChangeEvent, FormEvent, useState } from "react";
import styles from "../styles/Home.module.css";

type Talk = {
  title: string;
  abstract: string;
};

type Errors = {
  title: string | null;
  abstract: string | null;
};

const newTalk: Talk = {
  title: "",
  abstract: "",
};

type Status = "Idle" | "Submitted" | "Complete";

export default function Home() {
  const [status, setStatus] = useState<Status>("Idle");
  const [talk, setTalk] = useState(newTalk);

  // Derived state
  const errors = validate();

  function onChange(
    event: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
  ) {
    setTalk({ ...talk, [event.target.id]: event.target.value });
  }

  function validate() {
    const errors: Errors = {
      abstract: null,
      title: null,
    };
    if (status === "Submitted" && !talk.title) {
      errors.title = "Title is required.";
    }
    if (status === "Submitted" && !talk.abstract)
      errors.abstract = "Abstract is required.";
    return errors;
  }

  function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); // stop postback
    setStatus("Submitted");
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>ConnectTech 2021</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Speak at ConnectTech!</h1>

        <form onSubmit={handleSubmit}>
          <h2>Submit a talk</h2>
          <div>
            <label htmlFor="title">Title</label>
            <br />
            <input
              type="text"
              id="title"
              value={talk.title}
              onChange={onChange}
            />
            {errors.title && <p>{errors.title}</p>}
          </div>
          <div>
            <label htmlFor="abstract">Abstract</label>
            <br />
            <textarea id="abstract" value={talk.abstract} onChange={onChange} />
            {errors.abstract && <p>{errors.abstract}</p>}
          </div>
          <input type="submit" value="Submit talk" />
        </form>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
